# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Accueil"
#  url = "#about"
#  weight = 10

[[main]]
  name = "Blog"
  url = "https://lydericblog.wordpress.com/"
  weight = 100

[[main]]
  name = "Livres"
	identifier = "menu-livres"
  url = "livres"
  weight = 200

[[main]]
  name = "L'essuie-main de l'empereur"
	parent = "menu-livres"
	url = "https://liberinvictus.com/modus/"
	weight = 205

[[main]]
  name = "Le cartable d'Ollie"
	parent = "menu-livres"
	url = "https://liberinvictus.com/le-cartable-dollie/"
	weight = 210

[[main]]
  name = "Contact"
  url = "contact"
  weight = 300
